<a href="https://colab.research.google.com/github/skhabiri/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/skhabiri_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [1]:
# YOUR WORK HERE
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
!unzip student.zip
from scipy import stats
import pandas as pd
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

--2020-06-10 01:22:09--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-06-10 01:22:09 (321 KB/s) - ‘student.zip’ saved [20478/20478]

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             
(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [0]:
# YOUR WORK HERE
def mychi2(df, name1, name2, info):
  """ info is a boolean value that prints more information
  about the chi2 statistic"""
  
  contingency = pd.crosstab(df[name1], df[name2])
  chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

  if p_value<0.05:
    print("Null hypothesis for ",name1," and ",name2," is rejected \n chi2:",chi2,"\n p_val: ",p_value )
  else:
    print("Null hypothesis for ",name1," and ",name2," is not rejected \n chi2:",chi2,"\n p_val: ",p_value )
  
  if info:
    print("************")
    print(df[name1].value_counts().sort_index())
    print(df[name2].value_counts().sort_index())
    print("chi2 statistic", chi2)
    print("p value", p_value)
    print("degrees of freedom",dof)
    print("expected frequencies table", expected)
    print(" Here is the cross table: \n")
    return contingency


In [3]:
chi2_labels = ["sex","age","famsize","studytime","failures"]
for label_i in chi2_labels:
  for label_j in chi2_labels:
    mychi2(df,label_i,label_j,False)


Null hypothesis for  sex  and  sex  is rejected 
 chi2: 390.9988461440834 
 p_val:  5.016813439124192e-87
Null hypothesis for  sex  and  age  is not rejected 
 chi2: 5.99460281380294 
 p_val:  0.5403796955381378
Null hypothesis for  sex  and  famsize  is not rejected 
 chi2: 2.8048454063998163 
 p_val:  0.09397990309173032
Null hypothesis for  sex  and  studytime  is rejected 
 chi2: 50.634037705651764 
 p_val:  5.854045926336989e-11
Null hypothesis for  sex  and  failures  is not rejected 
 chi2: 3.5302645725647808 
 p_val:  0.31685806856495097
Null hypothesis for  age  and  sex  is not rejected 
 chi2: 5.99460281380294 
 p_val:  0.5403796955381378
Null hypothesis for  age  and  age  is rejected 
 chi2: 2765.0 
 p_val:  0.0
Null hypothesis for  age  and  famsize  is not rejected 
 chi2: 3.3427362331429626 
 p_val:  0.851591182655544
Null hypothesis for  age  and  studytime  is not rejected 
 chi2: 21.005026189849133 
 p_val:  0.45863728792691505
Null hypothesis for  age  and  failures

In [4]:
mychi2(df,"famsize","studytime", True)

Null hypothesis for  famsize  and  studytime  is rejected 
 chi2: 11.09435481782051 
 p_val:  0.011226452773765971
************
GT3    281
LE3    114
Name: famsize, dtype: int64
1    105
2    198
3     65
4     27
Name: studytime, dtype: int64
chi2 statistic 11.09435481782051
p value 0.011226452773765971
degrees of freedom 3
expected frequencies table [[ 74.69620253 140.8556962   46.24050633  19.20759494]
 [ 30.30379747  57.1443038   18.75949367   7.79240506]]
 Here is the cross table: 



studytime   1    2   3   4
famsize                   
GT3        74  131  57  19
LE3        31   67   8   8

In [5]:
mychi2(df,"sex","failures",True)

Null hypothesis for  sex  and  failures  is not rejected 
 chi2: 3.5302645725647808 
 p_val:  0.31685806856495097
************
F    208
M    187
Name: sex, dtype: int64
0    312
1     50
2     17
3     16
Name: failures, dtype: int64
chi2 statistic 3.5302645725647808
p value 0.31685806856495097
degrees of freedom 3
expected frequencies table [[164.29367089  26.32911392   8.95189873   8.42531646]
 [147.70632911  23.67088608   8.04810127   7.57468354]]
 Here is the cross table: 



failures    0   1   2   3
sex                      
F         168  23  11   6
M         144  27   6  10

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE

import numpy as np

In [0]:
def mychi2_man(df, name1, name2):
  observed=pd.crosstab(df[name1], df[name2])
  observed_with_margins = pd.crosstab(df[name1], df[name2], margins=True)
  row_totals = observed_with_margins.iloc[-1, :-1].values
  col_totals = observed_with_margins.iloc[:-1, -1].values
  sample_size = df.shape[0]
  expected = np.zeros((len(df[name1].value_counts()),len(df[name2].value_counts())))
  for j, col in enumerate(col_totals):
    for i, row in enumerate(row_totals): 
      expected_value = (row*col / sample_size)
      # print(expected_value, i, j,'\n')
      expected[j][i] = expected_value
  observed_arr = observed.to_numpy()
  chi2 = ((observed_arr - expected)**2 / expected).sum()
  dof = (len(df[name1].value_counts())-1)*(len(df[name2].value_counts())-1)
  print("Use the chi2 statistics to get the pval")
  return observed_arr, expected, chi2, dof


In [8]:
observed, expected, chi2, dof = mychi2_man(df, "sex","failures")
print("chi2 statistic", chi2)
print("degrees of freedom",dof)
print("expected frequencies table", expected)
print(" Here is the cross table: \n")
observed


Use the chi2 statistics to get the pval
chi2 statistic 3.5302645725647808
degrees of freedom 3
expected frequencies table [[164.29367089  26.32911392   8.95189873   8.42531646]
 [147.70632911  23.67088608   8.04810127   7.57468354]]
 Here is the cross table: 



array([[168,  23,  11,   6],
       [144,  27,   6,  10]])

In [10]:
observed, expected, chi2, dof = mychi2_man(df,"studytime", "famsize")
print("chi2 statistic", chi2)
print("degrees of freedom",dof)
print("expected frequencies table", expected)
print(" Here is the cross table: \n")
observed

Use the chi2 statistics to get the pval
chi2 statistic 11.094354817820511
degrees of freedom 3
expected frequencies table [[ 74.69620253  30.30379747]
 [140.8556962   57.1443038 ]
 [ 46.24050633  18.75949367]
 [ 19.20759494   7.79240506]]
 Here is the cross table: 



array([[ 74,  31],
       [131,  67],
       [ 57,   8],
       [ 19,   8]])



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)